services:
  oracle-db:
    container_name: oracle-db
    image: gvenzl/oracle-xe
    networks:
      - backend-networks
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: admin
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' > /dev/null"]
      interval: 10s
      retries: 10
      start_period: 30s

  backend:
    container_name: user-management-backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - backend-networks
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  oracle-data: 
    driver: local

networks:
  backend-networks:
    driver: bridge