@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcHJpbmctZWNvc3Npc3RlbWEiLCJzdWIiOiJhbGV4YW5MaW1hQEVtcHJlc2EuY29tIiwiZXhwIjoxNzU3MzQwOTQ3LCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl19.11waRXAikPttztLaPeaWf4ZSSZd-Gnw1hEf5BNt3K-I

# Login
POST {{hostname}}/api/auth/login
content-type: {{contentType}}

{
	"email": "alexanLima@Empresa.com",
	"password" : "senhaADMIN1@"
}

#EXEMPLOS: 
# "ADMIN"
# {
#     "email": "tedFerry@Empresa.com",
#     "password" : "senhaADMIN1@"
# }

# "USER"
# {
#     "email": "eduardTesoura@Empresa.com",
#     "password" : "senhaUSER1@"
# }

# {
#   "email": "bobEsponja@Empresa.com",
#     "password": "senhaUSER1@1"
# }
###
###

# Registrando novo usuário
POST {{hostname}}/v1/users
content-type: {{contentType}}
Authorization: {{token}}

{
    "fullName": "Bob Esponja",
    "email": "bobEsponja@Empresa.com",
    "password": "senhaUSER1@",
    "status": "EXPIRADO",
	"role": "USER"
}
###

# Listando todos os usuários
GET {{hostname}}/v1/users
Authorization: {{token}}
###

# Buscando usuário por id
GET {{hostname}}/v1/users/9571bd24-fa54-49ab-bb96-4a73307909c0
Authorization: {{token}}
###

# Listando usuarios com perfil e tentativas de logins
GET {{hostname}}/v1/users/allWithProfileAndAttempts
Authorization: {{token}}
###

# Atualizando os dados do usuário
PUT {{hostname}}/v1/users/9571bd24-fa54-49ab-bb96-4a73307909c0
content-type: {{contentType}}
Authorization: {{token}}

{
    "fullName": "Bob Esponja Quadrada",
    "email": "bob@Empresa.com"
}
###

# Atualizando o status do usuário
@id = 1
@status = "INATIVO"
PUT {{hostname}}/v1/users/{{id}}/{{status}}
content-type: {{contentType}}
Authorization: {{token}}
###

# Deletando um usuário
@id = 1
DELETE {{hostname}}/v1/users/{{id}}
Authorization: {{token}}
###

# Listando novos usuários 
GET {{hostname}}/v1/users/new
Authorization: {{token}}
###

#
POST {{hostname}}/v1/users/filter
Content-Type: {{contentType}}
Authorization: {{token}}

{
"fullName": null,
"email": null,
"status": null,
"createBy": "2025-08-25T16:50:02.93011",
"createUntil": "2025-08-28T12:26:02.915243"
}
###