# ===============================
# Configuração da aplicação
# ===============================
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# ===============================
# Configuração do servidor
# ===============================
server:
  port: 9090 # Porta onde o servidor irá rodar

# ===============================
# Configuração de logs
# ===============================
logging: # Nível de log para as classes do Spring Framework (INFO, DEBUG, ERROR, etc.)
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#=============================================
# Configuração do Actuator
#=============================================
management: 
  endpoints:
    access:
      default: NONE #Desabilita todos os Endpoints do Actuator
    web:
      base-path: / #Mudando o path do actuador de /actuator/<endpoint-actuator> para /<endpoint-actuator>
      exposure:
        # Exposição dos endpoints do Actuator
        # A configuração abaixo expõe apenas os endpoints de health, info e metrics
        # e desabilita a exposição pública de metrics
        # Para expor outros endpoints, adicione-os à lista
        # Exemplo: exposure.include: "health, info, metrics, env"
        include: "health, info, metrics"
  endpoint: 
    health: 
      access: READ_ONLY 
    info:
      access: READ_ONLY 
    metrics:
      access: NONE 


# ===============================
# Configuração do security JWT
# ===============================
jwt:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key} # Chave secreta para assinar o token JWT
      expiration: 3600000 # Tempo de expiração do token em milissegundos
      header: Authorization # Nome do cabeçalho HTTP onde o token JWT será enviado
      prefix: Bearer # Prefixo do token JWT no cabeçalho HTTP
      issuer: @project.name@ # Emissor do token JWT 
      roles: # Papéis permitidos no token JWT
        ADMIN
        USER

# ===============================
# Configuração do Banco de Dados Oracle
#================================
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

#==============================
# Configuração do JPA e Hibernate
#==============================
  jpa:
      hibernate:
        ddl-auto: validate # Atualiza o esquema do banco de dados automaticamente
        show-sql: true # Exibe as consultas SQL no console
      properties:
        hibernate:
          dialect: org.hibernate.dialect.OracleDialect #Dialeto do banco de dados Oracle
          format_sql: true # Formata as consultas SQL exibidas no console
          use_sql_comments: true # Adiciona comentários às consultas SQL
      database-platform: org.hibernate.dialect.OracleDialect # Dialeto do banco de dados Oracle
      open-in-view: false # Desabilita o Open EntityManager in View para evitar problemas de LazyInitializationException
      generate-ddl: true # Gera o DDL (Data Definition Language) para o banco de dados
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Estratégia de nomenclatura física padrão do Hibernate
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl # Estratégia de nomenclatura implícita legada do JPA
#==============================
# Configuração do Flyway
#==============================
  flyway:
    enabled: true
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    user: admin
    password: admin
    baseline-on-migrate: true