-- CRIAÇÃO DAS TABELAS

-- USUARIOS:
create table users (
   id           number
      generated by default on null as identity,
   username     varchar2(80) not null,
   email        varchar2(80) unique not null,
   passwd       varchar2(100) not null,
   status       number(1) default 0,
   creationdate timestamp default current_timestamp,
   role         varchar2(10) not null,
   constraint pk_users primary key ( id )
);

-- PERFIS DE USUARIOS:
create table profiles (
   id         number
      generated by default on null as identity,
   user_id    number,
   bio        varchar2(255),
   avatar_url varchar2(255),
   constraint pk_profiles primary key ( id ),
   constraint fk_profiles_user foreign key ( user_id )
      references users ( id )
);

-- REGISTRO DE TENTATIVAS DE LOGIN:
create table login_attempts (
   id           number
      generated by default on null as identity,
   user_id      number not null,
   attempt_time timestamp default current_timestamp,
   success      number(1) default 0,
   constraint pk_login_attempts primary key ( id ),
   constraint fk_login_user foreign key ( user_id )
      references users ( id )
);

-- CRIAÇÃO DOS ÍNDICES

-- Índices para profiles
create index idx_profiles_user_id on
   profiles (
      user_id
   );

-- Índices para users
create index idx_users_email on
   users (
      email
   );

-- Índices para login_attempts
create index idx_login_user_id on
   login_attempts (
      user_id
   );